### ISSUE TITLE
[CI/CD] Setup automated running of tests

### ISSUE THREAD

**Issue by s1m0000n** [vsha96/mllib#21]
**Is your feature request related to a problem? Please describe.**
It's just a good practice to make sure that tests are ok before merging new stuff. This would allow to rely at least on some checks to say that the main branch is probably relatively stable.

**Describe the solution you'd like**
1. Setup a Github Action to run `stack test` on the freshly checked out branches in pull requests
2. Make this a necessary condition before merging on pull requests

**Describe alternatives you've considered**
Of course, you can try trusting the devs of the project, but it's always safer for everybody to be sure, that at least the basics are not broken

**Additional context**
This is just a great practice to be picked

**Comment by vsha96** [comment]
Thank you! I will set this up soon
