### ISSUE TITLE
Consider developing preprocessing utils

### ISSUE THREAD

**Issue by s1m0000n** [vsha96/mllib#9]
**Is your feature request related to a problem? Please describe.**
In data science efficient data preprocessing makes more than 50% of success. EDA, transforming data from different mediums is sometimes even more important than a model with high "knowledge" capacity. @vsha96, for example, do you remember the task on ML Course at the 8th semester of CMC MSU? It was all about making decent preprocessing & feature engineering.

**Describe the solution you'd like**
I have some ideas on how it could be implemented. It would probably be great to have parallel & lazy data loaders implementing at least the most essential stuff:
- Data Containers like Pandas DataFrame, Series, based on fast implementations of arrays / lists
- EDA Tools: basic statistics like variance, std, mean etc., permutation & bootstrap testing, filling n/a values with statistics, Pirson & Spearman corellations, covariations
- At least basic text featurizers: tokenization, tf-idf / bm25, (naive bayes?), symbolic distances (these do not require a lot work, but are essential for many data-driven stuff)
- Data Loaders with batching, sampling, etc.
- Maybe PCA, t-SNE
- Maybe some bindings to simple visualization

**Describe alternatives you've considered**
Investigate current solutions, take curtain steps to make the library highly compatible with the most popular solutions. Orrr... start developing own solution!

**Comment by s1m0000n** [comment]
Probably this is out of the scope of this library, or isn't it?

**Comment by s1m0000n** [comment]
csv, json & other popular file format loading should probably implemented for containers

**Comment by vsha96** [comment]
Great idea! Some of this should appear in our library after we deal with #7, #8 and add parameters and data validation to the models. After this step we can use the models on data for example from [kaggle](https://www.kaggle.com/datasets). Therefore, next step will be data loading (into formats you mentioned) and preprocessing.

I will summarize the steps that we need to do:
1) close tickets #7, #8 
2) add parameters and data validation (there we can add tests, such as dimension checking)
3) add data loading
4) ...

After each step I will open a ticket on the [issue tracker](https://github.com/vsha96/mllib/issues) to coordinate further.

**Comment by s1m0000n** [comment]
I think that this is a great plan! So, I guess, the issues should be opened for each small step & this meta-issue should be closed for now
